import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "John Doe",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Jane Doe",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    // Adult dog 1
    {
      name: "Love 'em air dried beef liver",
      slug: "love-em-air-dried-beef-liver",
      categoryId: "b2988c4a-2c54-421e-94b4-d52670554b91",
      description:
        "Treat your furry friend to the rich, savory taste of Love 'em air dried beef liver. Packed with protein and essential nutrients, this delicious snack is perfect for training or just showing your pet some extra love.",
      images: [
        "/images/sample-products/da1.webp",
        "/images/sample-products/da1-2.webp",
      ],
      price: 14.99,
      brand: "Love 'em",
      rating: 4.1,
      numReviews: 25,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    // Adult dog 2
    {
      name: "Chicken with rice",
      slug: "chicken-with-rice",
      categoryId: "b2988c4a-2c54-421e-94b4-d52670554b91",
      description:
        "A wholesome meal of chicken with rice, perfect for adult dogs. Rich in protein and essential nutrients.",
      images: [
        "/images/sample-products/da2.webp",
        "/images/sample-products/da2-2.webp",
      ],
      price: 12.99,
      brand: "Advance",
      rating: 3.5,
      numReviews: 18,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Adult dog 3
    {
      name: "Royal Canin Digestive care",
      slug: "royal-canin-digestive-care",
      categoryId: "b2988c4a-2c54-421e-94b4-d52670554b91",
      description:
        "Royal Canin Digestive Care is designed to support your dog's digestive health with high-quality ingredients.",
      images: [
        "/images/sample-products/da3.webp",
        "/images/sample-products/da3-2.webp",
      ],
      price: 29.99,
      brand: "Royal Canin",
      rating: 4.3,
      numReviews: 30,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    // Adult dog 4
    {
      name: "Purina ONE SmartBlend",
      slug: "purina-one-smartblend",
      categoryId: "b2988c4a-2c54-421e-94b4-d52670554b91",
      description: "Purina ONE SmartBlend provides balanced nutrition for your dog with real meat as the first ingredient.",
      images: ["/images/sample-products/da-4.avif"],
      price: 24.99,
      brand: "Purina",
      rating: 3.8,
      numReviews: 22,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    // Puppy dog 1
    {
      name: "Turkey fillet treats",
      slug: "turkey-fillet-treats",
      categoryId: "03c83fbf-d0d2-453e-84fa-3c6935c63ff6",
      description: "Delicious turkey fillet treats for your puppy, rich in protein and perfect for training.",
      images: ["/images/sample-products/dp1.webp"],
      price: 9.99,
      brand: "Prime100",
      rating: 2.9,
      numReviews: 15,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    // Puppy dog 2
    {
      name: "Royal canin dry food puppy",
      slug: "royal-canin-dry-food-puppy",
      categoryId: "03c83fbf-d0d2-453e-84fa-3c6935c63ff6",
      description: "Royal Canin dry food for puppies provides balanced nutrition for growing dogs.",
      images: [
        "/images/sample-products/dp2.webp",
        "/images/sample-products/dp2-2.webp",
      ],
      price: 34.99,
      brand: "Royal Canin",
      rating: 4.0,
      numReviews: 28,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    // Puppy dog 3
    {
      name: "Royal canin daschund dry food puppy",
      slug: "royal-canin-daschund-dry-food-puppy",
      categoryId: "03c83fbf-d0d2-453e-84fa-3c6935c63ff6",
      description: "Specially formulated dry food for Daschund puppies by Royal Canin.",
      images: [
        "/images/sample-products/dp3.webp",
        "/images/sample-products/dp3-2.webp",
      ],
      price: 36.99,
      brand: "Royal Canin",
      rating: 3.7,
      numReviews: 20,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    // Special care dog 1
    {
      name: "Advocate fleas heartworm and worm medicine",
      slug: "advocate-fleas-heartworm-worm-medicine",
      categoryId: "f737d8e0-e1b5-435c-ab81-3c83947968d9",
      description: "Comprehensive treatment for fleas, heartworm, and worms in dogs.",
      images: ["/images/sample-products/ds1.webp"],
      price: 49.99,
      brand: "Advocate",
      rating: 4.2,
      numReviews: 35,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    // Special care dog 2
    {
      name: "NexGard spectra parasite treatment",
      slug: "nexgard-spectra-parasite-treatment",
      categoryId: "f737d8e0-e1b5-435c-ab81-3c83947968d9",
      description: "NexGard Spectra provides broad-spectrum parasite protection for dogs.",
      images: [
        "/images/sample-products/ds2.webp",
        "/images/sample-products/ds2-2.webp",
      ],
      price: 54.99,
      brand: "NexGard",
      rating: 3.9,
      numReviews: 40,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    // Kitten 1
    {
      name: "Grilled Chicken Fillet treat",
      slug: "grilled-chicken-fillet-treat",
      categoryId: "3c7db759-08ce-4a42-a805-9c0ecb1d49f4",
      description: "Tasty grilled chicken fillet treats for kittens, perfect for rewarding good behavior.",
      images: [
        "/images/sample-products/ck1.webp",
        "/images/sample-products/ck1-2.webp",
      ],
      price: 7.99,
      brand: "INABA",
      rating: 3.5,
      numReviews: 18,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Kitten 2
    {
      name: "Royal Canin 12 pack chicken chunks in jelly",
      slug: "royal-canin-12-pack-chicken-chunks-in-jelly",
      categoryId: "3c7db759-08ce-4a42-a805-9c0ecb1d49f4",
      description: "Royal Canin chicken chunks in jelly, a delicious and nutritious meal for kittens.",
      images: [
        "/images/sample-products/ck2.webp",
        "/images/sample-products/ck2-2.webp",
      ],
      price: 24.99,
      brand: "Royal Canin",
      rating: 3.8,
      numReviews: 22,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    // Kitten 3
    {
      name: "Purina Pro plan chicken formula",
      slug: "purina-pro-plan-chicken-formula",
      categoryId: "3c7db759-08ce-4a42-a805-9c0ecb1d49f4",
      description: "Purina Pro Plan chicken formula provides balanced nutrition for growing kittens.",
      images: [
        "/images/sample-products/ck3.webp",
        "/images/sample-products/ck3-2.webp",
      ],
      price: 29.99,
      brand: "Purina",
      rating: 3.6,
      numReviews: 25,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    // Cat adult 1
    {
      name: "Royal Canin home life dry food moderate calorie",
      slug: "royal-canin-home-life-dry-food-moderate-calorie",
      categoryId: "ae6eff32-a51d-455d-8db7-7cdba9461df0",
      description: "Royal Canin dry food for adult cats, moderate calorie formula for maintaining a healthy weight.",
      images: [
        "/images/sample-products/ca1.webp",
        "/images/sample-products/ca1-2.webp",
      ],
      price: 34.99,
      brand: "Royal Canin",
      rating: 4.0,
      numReviews: 30,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    // Cat adult 2
    {
      name: "Fancy feast petite delights triple flavor pack",
      slug: "fancy-feast-petite-delights-triple-flavor-pack",
      categoryId: "ae6eff32-a51d-455d-8db7-7cdba9461df0",
      description: "Fancy Feast Petite Delights, a triple flavor pack for adult cats.",
      images: [
        "/images/sample-products/ca2.webp",
        "/images/sample-products/ca2-2.webp",
      ],
      price: 19.99,
      brand: "Purina",
      rating: 3.6,
      numReviews: 20,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    // Cat adult 3
    {
      name: "Dine tuna & chicken",
      slug: "dine-tuna-chicken",
      categoryId: "ae6eff32-a51d-455d-8db7-7cdba9461df0",
      description: "Dine tuna & chicken, a delicious meal for adult cats.",
      images: [
        "/images/sample-products/ca3.webp",
        "/images/sample-products/ca3-2.webp",
      ],
      price: 22.99,
      brand: "Dine",
      rating: 3.7,
      numReviews: 18,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Cat special 1
    {
      name: "Bravecto flea tick and worm medicine",
      slug: "bravecto-flea-tick-worm-medicine",
      categoryId: "ff9e074c-4855-45b8-a2a1-091e42ea8552",
      description: "Bravecto provides comprehensive protection against fleas, ticks, and worms for cats.",
      images: [
        "/images/sample-products/cs1.webp",
        "/images/sample-products/cs1-2.webp",
      ],
      price: 54.99,
      brand: "Bravecto",
      rating: 4.0,
      numReviews: 28,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    // Cat special 2
    {
      name: "Royal canin urinary care molases in gravy",
      slug: "royal-canin-urinary-care-molases-in-gravy",
      categoryId: "ff9e074c-4855-45b8-a2a1-091e42ea8552",
      description: "Royal Canin urinary care molasses in gravy, designed to support urinary health in cats.",
      images: [
        "/images/sample-products/cs2.webp",
        "/images/sample-products/cs2-2.webp",
      ],
      price: 29.99,
      brand: "Royal Canin",
      rating: 3.8,
      numReviews: 22,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    // Cat special 3
    {
      name: "Feline Greenies dental treats",
      slug: "feline-greenies-dental-treats",
      categoryId: "ff9e074c-4855-45b8-a2a1-091e42ea8552",
      description: "Feline Greenies dental treats help maintain your cat's oral health while providing a tasty snack.",
      images: [
        "/images/sample-products/cs3.webp",
        "/images/sample-products/cs3-2.webp",
      ],
      price: 12.99,
      brand: "Greenies",
      rating: 3.5,
      numReviews: 18,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Fish Saltwater 1
    {
      name: "Instant Ocean Sea salt",
      slug: "instant-ocean-sea-salt",
      categoryId: "3db5c4bf-f72b-46a3-a901-9d1815723cb8",
      description: "Instant Ocean Sea Salt is perfect for creating a healthy marine environment for your saltwater fish.",
      images: [
        "/images/sample-products/fs1.avif",
        "/images/sample-products/fs1-2.avif",
      ],
      price: 39.99,
      brand: "Instant Ocean",
      rating: 4.1,
      numReviews: 25,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    // Fish Saltwater 2
    {
      name: "Ocean Nutrition Prime Reef Flakes",
      slug: "ocean-nutrition-prime-reef-flakes",
      categoryId: "3db5c4bf-f72b-46a3-a901-9d1815723cb8",
      description: "Ocean Nutrition Prime Reef Flakes provide balanced nutrition for your saltwater fish.",
      images: [
        "/images/sample-products/fs2.avif",
        "/images/sample-products/fs2-2.avif",
      ],
      price: 19.99,
      brand: "Ocean Nutrition",
      rating: 3.9,
      numReviews: 20,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    // Fish Saltwater 3
    {
      name: "Instant Ocean Reef Crystals",
      slug: "instant-ocean-reef-crystals",
      categoryId: "3db5c4bf-f72b-46a3-a901-9d1815723cb8",
      description: "Instant Ocean Reef Crystals are designed to support the health and growth of your reef aquarium.",
      images: [
        "/images/sample-products/fs3.avif",
        "/images/sample-products/fs3-2.avif",
      ],
      price: 44.99,
      brand: "Instant Ocean",
      rating: 4.0,
      numReviews: 30,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    // Fish Tropical 1
    {
      name: "Tetra Min tropical flakes",
      slug: "tetra-min-tropical-flakes",
      categoryId: "a9866c6d-740d-45f5-af38-bdbb93396eac",
      description: "Tetra Min tropical flakes provide balanced nutrition for your tropical fish.",
      images: [
        "/images/sample-products/ft1.avif",
        "/images/sample-products/ft1-2.avif",
      ],
      price: 14.99,
      brand: "Tetra",
      rating: 3.7,
      numReviews: 18,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Fish Tropical 2
    {
      name: "API Freshwater Master Test Kit",
      slug: "api-freshwater-master-test-kit",
      categoryId: "a9866c6d-740d-45f5-af38-bdbb93396eac",
      description: "API Freshwater Master Test Kit helps you maintain optimal water conditions for your tropical fish.",
      images: [
        "/images/sample-products/ft2.avif",
        "/images/sample-products/ft2-2.avif",
      ],
      price: 29.99,
      brand: "API",
      rating: 3.8,
      numReviews: 22,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    // Fish Tropical 3
    {
      name: "Freeze Dried Bloodworms",
      slug: "freeze-dried-bloodworms",
      categoryId: "a9866c6d-740d-45f5-af38-bdbb93396eac",
      description: "Freeze Dried Bloodworms are a high-protein treat for your tropical fish.",
      images: ["/images/sample-products/ft3.avif"],
      price: 9.99,
      brand: "San Francisco Bay Brand",
      rating: 3.5,
      numReviews: 20,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    // Fish Freshwater 1
    {
      name: "Fuval Bug Bites",
      slug: "fuval-bug-bites",
      categoryId: "121509d0-5fa5-4392-923c-589ff7568dfd",
      description: "Fuval Bug Bites provide a nutritious diet for your freshwater fish.",
      images: [
        "/images/sample-products/ff1.avif",
        "/images/sample-products/ff1-2.avif",
      ],
      price: 14.99,
      brand: "Aqueon",
      rating: 3.8,
      numReviews: 12,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Fish Freshwater 2
    {
      name: "Fuval Bug Bites Insect Larvae",
      slug: "fuval-bug-bites-insect-larvae",
      categoryId: "121509d0-5fa5-4392-923c-589ff7568dfd",
      description: "Fuval Bug Bites Insect Larvae provide a nutritious diet for your freshwater fish.",
      images: [
        "/images/sample-products/ff2.avif",
        "/images/sample-products/ff2-2.avif",
      ],
      price: 16.99,
      brand: "Fuval",
      rating: 3.9,
      numReviews: 15,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    // Fish Freshwater 3
    {
      name: "Zoo Med Floating Betta Log",
      slug: "zoo-med-floating-betta-log",
      categoryId: "121509d0-5fa5-4392-923c-589ff7568dfd",
      description: "Zoo Med Floating Betta Log provides a fun and interactive environment for your Betta fish.",
      images: [
        "/images/sample-products/ff3.avif",
        "/images/sample-products/ff3-2.avif",
      ],
      price: 12.99,
      brand: "Zoo Med",
      rating: 3.7,
      numReviews: 10,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    // Bird parakeet 1
    {
      name: "Wild Harvest Daily Blend Millet",
      slug: "wild-harvest-daily-blend-millet",
      categoryId: "8477136d-58c0-46ab-a63a-57c1c2c62c2f",
      description: "Wild Harvest Daily Blend Millet provides essential nutrients for your parakeet.",
      images: [
        "/images/sample-products/bp1.avif",
        "/images/sample-products/bp1-2.avif",
      ],
      price: 9.99,
      brand: "Wild Harvest",
      rating: 3.6,
      numReviews: 14,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    // Bird parakeet 2
    {
      name: "Trill Millet Sprays",
      slug: "trill-millet-sprays",
      categoryId: "8477136d-58c0-46ab-a63a-57c1c2c62c2f",
      description: "Trill Millet Sprays provide a tasty and nutritious treat for your parakeet.",
      images: [
        "/images/sample-products/bp2.webp",
        "/images/sample-products/bp2-2.webp",
      ],
      price: 11.99,
      brand: "Trill",
      rating: 3.5,
      numReviews: 12,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    // Bird parakeet 3
    {
      name: "Trill Nutrivit multivitamin",
      slug: "trill-nutrivit-multivitamin",
      categoryId: "8477136d-58c0-46ab-a63a-57c1c2c62c2f",
      description: "Trill Nutrivit multivitamin provides essential vitamins and minerals for your parakeet.",
      images: [
        "/images/sample-products/bp3.webp",
        "/images/sample-products/bp3-2.webp",
      ],
      price: 13.99,
      brand: "Trill",
      rating: 3.7,
      numReviews: 15,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Bird parrot 1
    {
      name: "Nutri Blend Seeds",
      slug: "nutri-blend-seeds",
      categoryId: "892a0b74-85ad-4942-870a-d2fda5ce667c",
      description: "Nutri Blend Seeds provide a balanced diet for your parrot.",
      images: [
        "/images/sample-products/bparrot1.webp",
        "/images/sample-products/bparrot1-2.webp",
      ],
      price: 19.99,
      brand: "Vetafarm",
      rating: 3.8,
      numReviews: 18,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    // Bird parrot 2
    {
      name: "South American Conure Mix",
      slug: "south-american-conure-mix",
      categoryId: "892a0b74-85ad-4942-870a-d2fda5ce667c",
      description: "South American Conure Mix provides a balanced diet for your conure.",
      images: [
        "/images/sample-products/bparrot2.webp",
        "/images/sample-products/bparrot2-2.webp",
      ],
      price: 21.99,
      brand: "Vetafarm",
      rating: 3.9,
      numReviews: 20,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    // Bird parrot 3
    {
      name: "Small Parrot Nutrivit Millet Mix",
      slug: "small-parrot-nutrivit-millet-mix",
      categoryId: "892a0b74-85ad-4942-870a-d2fda5ce667c",
      description: "Small Parrot Nutrivit Millet Mix provides essential nutrients for your small parrot.",
      images: [
        "/images/sample-products/bparrot3.webp",
        "/images/sample-products/bparrot3-2.webp",
      ],
      price: 17.99,
      brand: "Trill",
      rating: 3.7,
      numReviews: 14,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    // Bird wild 1
    {
      name: "Woodpecker Seed Cake",
      slug: "woodpecker-seed-cake",
      categoryId: "57ddaaeb-1cff-480c-b050-3e6aa623bfcd",
      description: "Woodpecker Seed Cake provides essential nutrients for wild birds.",
      images: [
        "/images/sample-products/bw1.avif",
        "/images/sample-products/bw1-2.avif",
      ],
      price: 12.99,
      brand: "Kaytee",
      rating: 3.8,
      numReviews: 16,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    // Bird wild 2
    {
      name: "Natural Premium Shelled Peanuts",
      slug: "natural-premium-shelled-peanuts",
      categoryId: "57ddaaeb-1cff-480c-b050-3e6aa623bfcd",
      description: "Natural Premium Shelled Peanuts provide a nutritious treat for wild birds.",
      images: [
        "/images/sample-products/bw2.avif",
        "/images/sample-products/bw2-2.avif",
      ],
      price: 14.99,
      brand: "Brown's",
      rating: 3.7,
      numReviews: 12,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Bird wild 3
    {
      name: "Nut & Fruit Blend",
      slug: "nut-fruit-blend",
      categoryId: "57ddaaeb-1cff-480c-b050-3e6aa623bfcd",
      description: "Nut & Fruit Blend provides a balanced diet for wild birds.",
      images: [
        "/images/sample-products/bw3.avif",
        "/images/sample-products/bw3-2.avif",
      ],
      price: 16.99,
      brand: "Kaytee",
      rating: 3.9,
      numReviews: 18,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
  ],
  categories: [
    {
      name: "all",
    },
    {
      name: "cat",
      subcategories: [
        { name: "kitten" },
        { name: "adult" },
        { name: "special care" },
      ],
    },
    {
      name: "dog",
      subcategories: [
        { name: "puppy" },
        { name: "adult" },
        { name: "special care" },
      ],
    },
    {
      name: "fish",
      subcategories: [
        { name: "freshwater" },
        { name: "saltwater" },
        { name: "tropical and exotic" },
      ],
    },
    {
      name: "bird",
      subcategories: [
        { name: "parakeet" },
        { name: "wild bird" },
        { name: "parrot" },
      ],
    },
  ],
};

export default sampleData;
